### PR TITLE
Add a self-check GHA workflow

### PR DESCRIPTION
**Pull request by webknjaz**
I think it's useful to have embedded self-checks. Also, it looks like GH advertises this way of testing atm.

### CODE REVIEW

**Comment by asottile** [comment]
I don't think this is valuable, it'll just invite noisy PRs for unnecessary updates (new python version, new OS version, etc.) when in reality the code here probably won't ever change (and when it does change, I just validate it upon release with an external repository)

plus the `master` branch isn't actually runnable (intentionally, you'd have to check in node_modules which is gross)

**Comment by webknjaz** [comment]
Yeah, I see. But also do you have anything external that acts as an integration test? It's currently undocumented what things work where. Like a full matrix.

**Comment by webknjaz** [comment]
Even now trying to figure out that matrix is a lot of try&error. It's valuable when there's some live example showing that "look, this is what actually works"

**Comment by asottile** [comment]
yeah there's a section in [the README](https://github.com/deadsnakes/action#available-versions)

**Comment by asottile** [comment]
there's no value in an integration test when there's essentially zero moving parts and very infrequent code changes

**Comment by webknjaz** [comment]
That section doesn't say that some of the versions won't work under certain OSs and doesn't mention that `apt` outputs misleading promises to console. Look: https://github.com/deadsnakes/action/pull/6/checks?check_run_id=778396303#step:4:23.

```console
  Supported Ubuntu and Python Versions
  ====================================
  
  - Ubuntu 16.04 (xenial) Python 2.3 - Python 2.6, Python 3.1 - Python3.4, Python 3.6 - Python3.9
```

**Comment by asottile** [comment]
sure but the section directly above it says `ubuntu-latest` -- it's not this repository's fault that `add-apt-repository` is broken in 16.04

**Comment by webknjaz** [comment]
I hear you. But `ubuntu-latest` is also a moving target. Now it's 18.04, once 20.04 is out of preview, it'll move there. Meaning that the README instructions will have a different meaning at different points in time.

**Comment by asottile** [comment]
>= 18.04 works fine, 16.04 is the only problem afaik

**Comment by webknjaz** [comment]
> >= 18.04 works fine, 16.04 is the only problem afaik

Checking... But still update to README would be great. "latest" just means "some version" w/o a context.

**Comment by webknjaz** [comment]
Looks like Python 3.7 + Ubuntu 20 also explodes: https://github.com/deadsnakes/action/pull/6/checks?check_run_id=778423270#step:4:90

**Comment by asottile** [comment]
> Looks like Python 3.7 + Ubuntu 20 also explodes

3.8 and nightly also installs upstream's package: https://github.com/deadsnakes/nightly#available-packages

**Comment by webknjaz** [comment]
> 3.8 and nightly also installs upstream's package: https://github.com/deadsnakes/nightly#available-packages

Ah, this wasn't obvious from the action's description. Can we make README not imply that?

**Comment by asottile** [comment]
done

**Pull request closed without merging**
